import { usePage } from "@inertiajs/react";

const translations = {
    pt: {
        503: "Desculpe, estamos em manutenção. Volte em breve.",
        500: "Ops, algo deu errado em nossos servidores.",
        404: (url) =>
            `Desculpe, a página que você está procurando "<strong>${url}</strong>" não foi encontrada.`,
        403: (url) =>
            `Você não tem permissão para acessar esta página: <strong>${url}</strong>.`,
        back: "Voltar",
        abreEmNovaAba: "Abrir em nova guia",
        navegacaoLinhas: "Navegar entre linhas",
        linhaAnterior: "Linha anterior",
        proximaLinha: "Próxima linha",
        fecharFiltros: "Fechar filtros",
        home: "Home",
        sobre: "Sobre",
        nossosVinhos: "Nossos Vinhos",
        enoturismo: "Enoturismo",
        contato: "Contato",
        blog: "Blog",
        lojaVirtual: "Loja Virtual",
        whatsapp: "WhatsApp",
        verMapa: "Ver Mapa",
        nossasRedes: "Nossas redes",
        marcas: "Marcas",
        categorias: "Categorias",
        sustentabilidade: "Sustentabilidade",
        vinhos: "Vinhos",
        politicaPrivacidade: "Política de Privacidade",
        todosOsDireitosReservados: "Todos os direitos reservados",
        desenvolvidoPor: "Desenvolvido por",
        conhecaNossosVinhos: "Conheça nossos vinhos",
        conheca: "Conheça",
        verLinhaDoTempo: "Ver linha do Tempo",
        liEAceito: "Li e aceito a",
        enviar: "Enviar",
        enviarMensagem: "Enviar Mensagem",
        endereco4: "CEP ",
        localizacao: "Localização",
        composicaoDoSolo: "Composição do solo",
        clima: "Clima",
        arquitetura: "Arquitetura",
        agendeSuaExperiencia: "Agende sua Experiência",
        fale: "Fale",
        conosco: "Conosco",
        endereco: "Endereço",
        selecioneAreaContato: "Selecione a área de contato:",
        geral: "Geral",
        comercial: "Comercial",
        nomeCompleto: "Nome completo",
        email: "E-mail",
        telefone: "Telefone",
        digiteAqui: "Digite aqui...",
        sucesso: "Sucesso!",
        suaMensagemFoiEnviada: "Sua mensagem foi enviada.",
        verMaisVinhos: "Ver mais vinhos.",
        comprarAgora: "Comprar Agora",
        filtros: "Filtros",
        aplicarFiltros: "Aplicar Filtros",
        destaques: "Destaques",
        baixarFicha: "Baixar Ficha Técnica",
        fichaTecnica: "Ficha Técnica",
        colheitas: "Colheitas",
        areaRestrita: "Área Restrita",
        cookie: "Utilizamos cookies para oferecer uma melhor experiência, melhorar o desempenho, analisar como você interage em nosso site e personalizar conteúdo. Para mais informações acesse nossa",
        cookiePolitica: "política de privacidade",
        aceitarCookies: "Aceitar todos os cookies",
    },
    en: {
        503: "Sorry, we are doing some maintenance. Please check back soon.",
        500: "Oops, something went wrong on our servers.",
        404: (url) =>
            `Sorry, the page you are looking for "<strong>${url}</strong>" could not be found.`,
        403: (url) =>
            `Sorry, you are forbidden from accessing this page: <strong>${url}</strong>.`,
        back: "Back",
        abreEmNovaAba: "Open in a new tab",
        navegacaoLinhas: "Navigating between the lines",
        linhaAnterior: "Previous line",
        proximaLinha: "Next line",
        fecharFiltros: "Close filters",
        home: "Home",
        sobre: "About",
        nossosVinhos: "Our Wines",
        enoturismo: "Wine Tourism",
        contato: "Contact",
        blog: "Blog",
        lojaVirtual: "Virtual Store",
        whatsapp: "WhatsApp",
        verMapa: "View Map",
        nossasRedes: "Our medias",
        marcas: "Brands",
        categorias: "Categories",
        sustentabilidade: "Sustainability",
        vinhos: "Wines",
        politicaPrivacidade: "Privacy Policy",
        todosOsDireitosReservados: "All rights reserved",
        desenvolvidoPor: "Developed by",
        conhecaNossosVinhos: "Discover our wines",
        conheca: "Discover",
        verLinhaDoTempo: "View Timeline",
        liEAceito: "I have read and accept the",
        enviar: "Send",
        enviarMensagem: "Send Message",
        endereco4: "ZIP ",
        localizacao: "Location",
        composicaoDoSolo: "Soil Composition",
        clima: "Climate",
        arquitetura: "Architecture",
        agendeSuaExperiencia: "Schedule your experience",
        fale: "Talk",
        conosco: "to Us",
        endereco: "Address",
        selecioneAreaContato: "Select the contact area:",
        geral: "General",
        comercial: "Commercial",
        nomeCompleto: "Full name",
        email: "E-mail",
        telefone: "Phone",
        digiteAqui: "Type here...",
        sucesso: "Success!",
        suaMensagemFoiEnviada: "Your message has been sent.",
        verMaisVinhos: "See more wines.",
        comprarAgora: "Buy Now",
        filtros: "Filters",
        aplicarFiltros: "Apply Filters",
        destaques: "Highlights",
        baixarFicha: "Download Technical Sheet",
        fichaTecnica: "Technical Sheet",
        colheitas: "Harvests",
        areaRestrita: "Restrict Area",
        cookie: "We use cookies to provide a better experience, improve performance, analyze how you interact with our site, and personalize content. For more information, please visit our",
        cookiePolitica: "privacy policy",
        aceitarCookies: "Accept all cookies",
    },
};

export function useLang() {
    const { language, idioma } = usePage().props;

    return (key, value = null) => {
        const translation = translations[language ?? idioma]?.[String(key)];

        if (typeof translation === "function") {
            return translation(value);
        }

        return translation || key;
    };
}
